from .ingestion_service import IngestionService
from .rag_workflow import RAGWorkflowService
from .text_extraction_service import text_extraction_service as text_extraction_service
from .embedding_service import embedding_service as embedding_service
from .hierarchical_chunking_service import hierarchical_chunking_service as hierarchical_chunking_service
from .streaming_service import streaming_service as streaming_service
from .prompt_registry import prompt_registry as prompt_registry
from .ab_testing import ab_testing_framework as ab_testing_framework
from .finetuning_service import finetuning_service as finetuning_service
from .contradiction_service import contradiction_service as contradiction_service
from .knowledge_base_service import knowledge_base_service as knowledge_base_service
from .quantization_service import quantization_service as quantization_service
from .load_balancing_service import load_balancing_service as load_balancing_service
from .metadata_extraction_service import metadata_extraction_service as metadata_extraction_service

# Create singleton instances of the services that can be imported elsewhere
ingestion_service = IngestionService()
rag_workflow_service = RAGWorkflowService()
